export const EVENTS = {
    DWARF_HUNGRY: 'dwarf.hungry',
    DWARF_ATE: 'dwarf.ate',
    DWARF_TIRED: 'dwarf.tired',
    DWARF_ASLEEP: 'dwarf.asleep',
    DWARF_WOKE: 'dwarf.woke',
    WALL_DUG: 'wall.dug',
    WALL_BUILT: 'wall.built',
    TREE_CHOPPED: 'tree.chopped',
    ITEM_STORED: 'item.stored',
    CROP_HARVESTED: 'crop.harvested',
    GOBLIN_ARRIVED: 'goblin.arrived',
    MIGRANT_ARRIVED: 'migrant.arrived',
    DWARF_FLEES: 'dwarf.flees',
    DWARF_FIGHTS: 'dwarf.fights',
    DWARF_INJURED: 'dwarf.injured',
    DWARF_STARVING: 'dwarf.starving',
    DWARF_DIED: 'dwarf.died',
    GOBLIN_SLAIN: 'goblin.slain',
    DWARF_TANTRUM: 'dwarf.tantrum',
    DWARF_CALMED: 'dwarf.calmed',
    ITEM_SMASHED: 'item.smashed',
    FURNITURE_BUILT: 'furniture.built',
};
